[locations]
Ekoplaza = "9401HR"
Home = "9403EW"

[birthdays]
colour = 31

[work]
colour = 35

[personal]
colour = 34

[birthdays.24344797]
title = "Teije's birthday"
notes = "Happy Birthday!"
location = "9403EW"
date = "20/12/2022"
from = "00:00"
to = "00:00"

[work.19249676]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "18/12/2021"
from = "08:00"
to = "17:00"

[work.26240756]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "21/12/2021"
from = "08:00"
to = "18:00"

[work.19893370]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "23/12/2021"
from = "08:00"
to = "17:30"

[work.25785651]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "27/12/2021"
from = "09:00"
to = "18:00"

[work.18590837]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "28/12/2021"
from = "09:00"
to = "18:00"

[work.25216470]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "29/12/2021"
from = "08:00"
to = "18:00"

[work.25558995]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "07/01/2022"
from = "09:00"
to = "18:00"

[work.22401126]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "08/01/2022"
from = "08:00"
to = "17:00"

[work.10340186]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "15/01/2022"
from = "08:00"
to = "17:00"

[work.43057809]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "22/01/2022"
from = "08:00"
to = "17:00"

[work.22029745]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "29/01/2022"
from = "08:00"
to = "17:00"

[work.23664059]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "05/02/2022"
from = "08:00"
to = "17:00"

[work.18997067]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "12/02/2022"
from = "08:00"
to = "17:00"

[work.51961667]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "24/02/2022"
from = "09:00"
to = "18:00"

[work.24476998]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "25/02/2022"
from = "09:00"
to = "18:00"

[work.13599054]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "26/02/2022"
from = "08:00"
to = "17:00"

[work.18114934]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "05/03/2022"
from = "08:00"
to = "17:00"

[work.11994901]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "12/03/2022"
from = "08:00"
to = "17:00"

[work.56982760]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "19/03/2022"
from = "08:00"
to = "17:00"

[work.58294841]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "26/03/2022"
from = "08:00"
to = "17:00"

[work.62990456]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "02/04/2022"
from = "08:00"
to = "17:00"

[work.26009966]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "09/04/2022"
from = "08:00"
to = "17:00"

[work.10098605]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "16/04/2022"
from = "08:00"
to = "17:00"

[work.68555468]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "23/04/2022"
from = "08:00"
to = "17:00"

[work.18533697]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "26/04/2022"
from = "09:00"
to = "18:00"

[work.18471735]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "28/04/2022"
from = "09:00"
to = "18:00"

[work.12628302]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "30/04/2022"
from = "08:00"
to = "17:00"

[work.14742388]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "03/05/2022"
from = "09:00"
to = "18:00"

[work.35297845]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "05/05/2022"
from = "09:00"
to = "18:00"

[work.47781503]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "07/05/2022"
from = "08:00"
to = "17:00"

[work.89660378]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "14/05/2022"
from = "08:00"
to = "17:00"

[work.15136046]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "21/05/2022"
from = "08:00"
to = "17:00"

[work.19331929]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "28/05/2022"
from = "08:00"
to = "17:00"

[work.14167479]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "04/06/2022"
from = "08:00"
to = "17:00"

[work.18675487]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "11/06/2022"
from = "08:00"
to = "17:00"

[work.56159925]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "18/06/2022"
from = "08:00"
to = "17:00"

[work.63417961]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "25/06/2022"
from = "08:00"
to = "17:00"

[work.25395147]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "02/07/2022"
from = "08:00"
to = "17:00"

[work.17446876]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "04/07/2022"
from = "09:00"
to = "18:00"

[work.43286068]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "05/07/2022"
from = "09:00"
to = "18:00"

[work.76886783]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "07/07/2022"
from = "09:00"
to = "18:00"

[work.40317347]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "08/07/2022"
from = "14:00"
to = "19:00"

[work.26779999]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "09/07/2022"
from = "08:00"
to = "17:00"

[work.39816641]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "11/07/2022"
from = "09:00"
to = "18:00"

[work.25864138]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "14/07/2022"
from = "09:00"
to = "18:00"

[work.36509846]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "15/07/2022"
from = "14:00"
to = "19:00"

[work.53874984]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "16/07/2022"
from = "08:00"
to = "17:00"

[work.10214227]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "18/07/2022"
from = "09:00"
to = "18:00"

[work.14655531]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "20/07/2022"
from = "09:00"
to = "18:00"

[work.11033169]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "22/07/2022"
from = "10:30"
to = "19:00"

[work.17123225]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "23/07/2022"
from = "08:00"
to = "17:00"

[work.18084459]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "26/07/2022"
from = "09:00"
to = "18:00"

[work.18835325]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "28/07/2022"
from = "09:00"
to = "18:00"

[work.25602172]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "29/07/2022"
from = "14:00"
to = "19:00"

[work.18151177]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "30/07/2022"
from = "08:00"
to = "17:00"

[work.16334817]
title = "Ekoplaza"
notes = ""
location = "9401HR"
date = "19/07/2022"
from = "09:00"
to = "18:00"
